### PR TITLE
fix: resolve secrets in OIDC provider configuration

### LINKED ISSUE #5131: OIDC credentials not able to pull from secrets file provider
Hello,

I'm currently using v2.4.0 of Flipt OSS.  I'd like to use the secrets file provider for retrieving the OIDC authentication provider credentials (i.e. client_id and client_secret).  The below configuration does not work for me.

```yaml
oidc:
  providers:
    keycloak:
      client_id: ${secret:file:clientid}
      client_secret: ${secret:file:clientsecret}
```

Hard coding the credentials works fine or using an environment variable such as the example below:

```yaml
oidc:
  providers:
    keycloak:
      client_id: ${env:CLIENT_ID}
      client_secret: ${env:CLIENT_SECRET}
```

The secrets file provider works fine with credentials.[I].access_token.

### PR DESCRIPTION
**Pull request by markphelps**
## Summary

Map values from `MapIndex()` are non-addressable in Go's reflection API, preventing secret references from being resolved in the `walkConfigForSecrets` function. This fix creates an addressable copy of struct map values, resolves secrets in the copy, and sets the modified value back into the map.

This enables using `${secret:file:...}` syntax in OIDC provider credentials configuration for `client_id` and `client_secret` fields.

## Changes

- **Modified `cmd/flipt/main.go`**: Fixed map value handling in `walkConfigForSecrets` to support secret resolution
- **Added `cmd/flipt/main_test.go`**: Added comprehensive tests for secret resolution in various scenarios

Fixes #5131

### CODE REVIEW

File: cmd/flipt/main_test.go [hunk 1]
```diff
@@ -0,0 +1,205 @@
...
+func TestWalkConfigForSecrets_SimpleField(t *testing.T) {
+	cfg := &testConfig{
+		SimpleField: "${secret:file:mykey}",
+	}
+
+	manager := newMockManager(map[string][]byte{
+		"file:mykey": []byte("resolved-value"),
+	})
+
+	err := walkConfigForSecrets(context.Background(), reflect.ValueOf(cfg).Elem(), manager)
```
Comment (erka) [inline cmd/flipt/main_test.go]:
```suggestion	
	err := walkConfigForSecrets(t.Context(), reflect.ValueOf(cfg).Elem(), manager)
```
