### PR TITLE
fix: prune remotes from cache that no longer exist

### LINKED ISSUE #4179: [Bug]: Git backend fails to poll when a reference no longer exists
### Bug Description

Every poll interval (30 secs) flipt fails to find a remote Git ref and in turn fails to update all other refs.

The ref still seems to be in the cache and while iterating over the cached refs it fails to gracefully handle a removed Git ref.
Probably here: https://github.com/flipt-io/flipt/blob/main/internal/storage/fs/git/store.go#L302

### Which major version?

v1

### Version Info

[v1.58.0](https://github.com/flipt-io/flipt/releases/tag/v1.58.0) via Helm

### Search

- [x] I searched for other open and closed issues before opening this

### Steps to Reproduce

- create a remote ref (feature branch)
- request an evaluation with this reference
- delete the remote feature branch

### Expected Behavior

Flipt should gracefully handle removed remote git refs that are not the "main" ref configured on startup. 

### Additional Context

```
message=2025-05-06T09:48:59Z [31mERROR[0m error getting file system from directory {"server": "grpc", "git_storage_type": "memory", "repository": "https://github.com/my-repo/my-flipt-config", "ref": "main", "error": "couldn't find remote ref \"refs/heads/add-more-flags\""}
```

### PR DESCRIPTION
**Pull request by markphelps**
Ok this should fix #4179

Previously we werent deleting refs from the cache if they could not be fetched. This causes an issue since fetch returns an error `error getting file system from directory` for any ref that does not exist upstream and continues to do so forever.

This changes the logic to now:

1. always prune on fetching which keeps the local refs in sync with upstream
2. list all the remote refs if fetch fails and then delete any of refs that exist in the cache that do not exist upstream

This should gracefully handle the case where a ref did exist in the cache but was then deleted upstream

### CODE REVIEW

File: internal/storage/fs/cache.go [hunk 1]
```diff
@@ -182,13 +184,27 @@ func (c *SnapshotCache[K]) References() []string {
...
+// Delete removes a reference from the snapshot cache.
+func (c *SnapshotCache[K]) Delete(ref string) {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+
+	if _, ok := c.fixed[ref]; ok {
+		delete(c.fixed, ref)
+		// No need to evict here, as fixed entries are not in LRU
+		return
+	}
```
Comment (GeorgeMac) [inline internal/storage/fs/cache.go:205]: Fixed should always be present as its configured via Flipt configuration.
If it is deleted in the upstream we have a problem (e.g. `main` is put in fixed).

**Review by GeorgeMac — APPROVED** [review]
Looks good to me. One comment on deleting fixed refs.
Could also be an explicit error case.
