### PR TITLE
fix(authz): added a helper function to the policy engine to simplify auth method verification

### LINKED ISSUE #3416: Authz rego policy represents method as enum (integer) value instead of string
I originally thought of this as a bug, though now I guess it is more just awkward.
Long story short, in order to scope a policy rule to a particular authentication method (i.e. OIDC or Token and so on), you have to know the enum value of the method.

```rego
allow if {
    input.authentication.method == 1 # token
}

allow if {
    input.authentication.method == 2 # oidc
}
```

See the enum definition in the proto for the correct numbers: https://github.com/flipt-io/flipt/blob/5c6de423ccaad9eda072d951c4fc34e779308e95/rpc/flipt/auth/auth.proto#L54-L62

I also thought we documented that you could compare the method to the string form (like so: `input.authentication.method == "METHOD_TOKEN"`). However, I now cannot see any documentation that teaches folks to do it this way.
So, really, I have been spreading misinformation here.

## Paths Forward

There are a few paths forward we could take. I think we should do something to make it either clearer or easier to scope rules to methods. Here are some ideas off the top of my head:

1. We document the enum values

This is the simplest one. We could document the proto enum values and how to do this kind of scoping today.
It is ugly and unclear in the policy cod, but achieavable. It does, however, mean we have to maintain it working in this way.

2. We change it to a string

We update the input to have the string form instead of the integer representation.
This would break anyone who managing to use it correctly today.

3. We add a helper function to the policy engine and encourage its usage

Im sure there is a way we could inject our own package helper function for identifying the method more clearly in the authz engine.
This could mean we continue to support (1) but also have a clearer, more readable form.
(E.g. using custom function in Go: https://www.openpolicyagent.org/docs/latest/extensions/)

```
allow if {
    isMethod(input, "oidc")
}
```

### PR DESCRIPTION
**Pull request by erka**
resolves #3416

### CODE REVIEW

File: internal/server/authz/engine/rego/engine.go [hunk 1]
```diff
@@ -134,7 +135,7 @@ func newEngine(ctx context.Context, logger *zap.Logger, opts ...containers.Optio
 
 	// being polling for updates to data if source configured
 	if engine.dataSource != nil {
-		go poll(ctx, engine.policySourcePollDuration, func() {
+		go poll(ctx, engine.dataSourcePollDuration, func() {
```
Comment (markphelps) [inline internal/server/authz/engine/rego/engine.go:138]: nice

**Review by markphelps — APPROVED** [review]
looks great! thank you!
